name: fsp_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  http_parser: ^4.1.2
  mime: ^2.0.0
  path: ^1.9.1
  shelf_cors_headers: ^0.1.5
  http: ^1.2.1
  postgres: ^2.6.2
  redis: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
