name: fsp_shared
version: 0.0.1
description: Shared models and utilities for FSP microservices.
environment:
  sdk: ^3.9.2

dependencies:
  json_annotation: ^4.9.0
  shelf: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  test: ^1.25.6
